"""Generate concrete web scraping demo outputs for review and handoff."""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import asdict
from html import escape
from pathlib import Path
from typing import Any

from .demo_monitor_static import STATIC_HTML
from .pipeline import group_items_into_events, monitored_items_from_event_seed
from .repository import load_sources
from .source_monitor import deduplicate_items, monitor_source_from_html


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, default=str), encoding="utf-8")


def write_markdown_summary(
    path: Path, summary: dict[str, Any], events: list[dict[str, Any]]
) -> None:
    lines = [
        "# Web Scraping Output Summary",
        "",
        "This file is generated by the deterministic web scraping output command.",
        "It shows concrete files produced by the MVP pipeline without relying on a",
        "web app or live network access.",
        "",
        "## Generated Outputs",
        "",
        f"- Source snapshot: `{summary['source_snapshot']}`",
        f"- Scraped monitored items: `{summary['scraped_items_file']}`",
        f"- Seed monitored items: `{summary['seed_items_file']}`",
        f"- Regulatory events: `{summary['events_file']}`",
        f"- Run summary: `{summary['summary_file']}`",
        "",
        "## Run Counts",
        "",
        f"- Sources loaded: {summary['sources_loaded']}",
        f"- Static scraped items: {summary['static_scraped_items']}",
        f"- Seed monitored items: {summary['seed_monitored_items']}",
        f"- Regulatory events: {summary['regulatory_events']}",
        "",
        "## Validation Status Counts",
        "",
    ]
    for status, count in summary["status_counts"].items():
        lines.append(f"- {status}: {count}")

    lines.extend(["", "## Priority Counts", ""])
    for priority, count in summary["priority_counts"].items():
        lines.append(f"- {priority}: {count}")

    lines.extend(["", "## Example Events", ""])
    for event in events[:5]:
        lines.extend(
            [
                f"### {event['event_title']}",
                "",
                f"- Status: {event['event_status']}",
                f"- Priority: {event['overall_priority']}",
                f"- Regulation area: {event['regulation_area']}",
                f"- Evidence count: {event['evidence_count']}",
                f"- Recommended attention: {event['recommended_attention']}",
                "",
                event["summary"],
                "",
            ]
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def event_badge(status: str) -> str:
    return {
        "A_OFFICIALLY_PUBLISHED": "Official publication",
        "B_OFFICIAL_DRAFT": "Official draft/guidance",
        "C_UNCONFIRMED_NEWS": "Trusted news warning",
    }.get(status, status)


def build_article_feed(
    static_items: list[Any],
    events: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    feed: list[dict[str, Any]] = []
    for item in static_items:
        feed.append(
            {
                "title": item.title,
                "source": item.source_name,
                "url": item.url,
                "kind": "scraped_item",
                "status": "SCRAPED_MONITORED_ITEM",
                "status_label": "Scraped monitored item",
                "priority": "Review",
                "regulation_area": item.regulation_area,
                "topic_labels": item.topic_labels,
                "summary": item.summary
                or "Detected from a deterministic source-monitoring HTML sample.",
                "recommended_attention": "Review extracted item",
            }
        )

    for event in events:
        evidence = event.get("evidence", [])
        primary_evidence = evidence[0] if evidence else {}
        feed.append(
            {
                "title": event["event_title"],
                "source": primary_evidence.get("source_name", "Regulatory seed data"),
                "url": event.get("primary_official_source_url") or primary_evidence.get("url"),
                "kind": "regulatory_event",
                "status": event["event_status"],
                "status_label": event_badge(event["event_status"]),
                "priority": event["overall_priority"],
                "regulation_area": event["regulation_area"],
                "topic_labels": event["topic_labels"],
                "summary": event["summary"],
                "recommended_attention": event["recommended_attention"],
            }
        )
    return feed


def write_article_feed_markdown(path: Path, feed: list[dict[str, Any]]) -> None:
    lines = [
        "# Regulatory Articles and News Feed",
        "",
        "This feed is generated from deterministic MVP demo data. It shows the kind",
        "of articles, official updates, draft guidance, and trusted warnings that",
        "the platform can normalize for review.",
        "",
    ]
    for item in feed:
        lines.extend(
            [
                f"## {item['title']}",
                "",
                f"- Source: {item['source']}",
                f"- Status: {item['status_label']}",
                f"- Priority: {item['priority']}",
                f"- Regulation area: {item['regulation_area']}",
                f"- Topics: {', '.join(item['topic_labels']) if item['topic_labels'] else 'not detected'}",
                f"- Link: {item['url'] or 'not available'}",
                "",
                item["summary"],
                "",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_article_feed_html(path: Path, feed: list[dict[str, Any]]) -> None:
    cards = []
    for item in feed:
        status_slug = item["status"].lower()
        topics = ", ".join(item["topic_labels"]) if item["topic_labels"] else "not detected"
        link = (
            f'<a class="source-link" href="{escape(item["url"])}">Open source</a>'
            if item.get("url")
            else '<span class="source-link muted">No source link</span>'
        )
        cards.append(
            f"""
            <article class="card {escape(status_slug)}">
              <div class="card-topline">
                <span class="badge">{escape(item["status_label"])}</span>
                <span class="priority">{escape(str(item["priority"]))}</span>
              </div>
              <h2>{escape(item["title"])}</h2>
              <p class="summary">{escape(item["summary"])}</p>
              <dl>
                <div><dt>Source</dt><dd>{escape(item["source"])}</dd></div>
                <div><dt>Area</dt><dd>{escape(item["regulation_area"])}</dd></div>
                <div><dt>Topics</dt><dd>{escape(topics)}</dd></div>
                <div><dt>Attention</dt><dd>{escape(item["recommended_attention"])}</dd></div>
              </dl>
              {link}
            </article>
            """
        )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Regulatory Articles and News Feed</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #172033;
      --muted: #5c667a;
      --line: #d8dee9;
      --surface: #ffffff;
      --page: #f4f6f9;
      --official: #0f766e;
      --draft: #8a5a00;
      --warning: #a23b3b;
      --scraped: #365899;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
      background: var(--page);
      color: var(--ink);
      line-height: 1.5;
    }}
    header {{
      padding: 32px 28px 22px;
      border-bottom: 1px solid var(--line);
      background: var(--surface);
    }}
    header h1 {{
      margin: 0 0 8px;
      font-size: 28px;
      letter-spacing: 0;
    }}
    header p {{
      max-width: 920px;
      margin: 0;
      color: var(--muted);
    }}
    main {{
      max-width: 1180px;
      margin: 0 auto;
      padding: 24px;
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 16px;
    }}
    .card {{
      background: var(--surface);
      border: 1px solid var(--line);
      border-left: 6px solid var(--scraped);
      border-radius: 8px;
      padding: 18px;
      min-height: 320px;
    }}
    .a_officially_published {{ border-left-color: var(--official); }}
    .b_official_draft {{ border-left-color: var(--draft); }}
    .c_unconfirmed_news {{ border-left-color: var(--warning); }}
    .card-topline {{
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: center;
      margin-bottom: 12px;
    }}
    .badge, .priority {{
      font-size: 12px;
      font-weight: 700;
      text-transform: uppercase;
      color: var(--muted);
    }}
    h2 {{
      margin: 0 0 10px;
      font-size: 19px;
      letter-spacing: 0;
    }}
    .summary {{
      margin: 0 0 16px;
      color: var(--ink);
    }}
    dl {{
      margin: 0 0 16px;
      display: grid;
      gap: 8px;
    }}
    dl div {{
      display: grid;
      grid-template-columns: 92px 1fr;
      gap: 10px;
    }}
    dt {{
      color: var(--muted);
      font-size: 13px;
    }}
    dd {{
      margin: 0;
      font-size: 13px;
    }}
    .source-link {{
      color: #174ea6;
      font-weight: 700;
      text-decoration: none;
    }}
    .muted {{ color: var(--muted); }}
  </style>
</head>
<body>
  <header>
    <h1>Regulatory Articles and News Feed</h1>
    <p>
      Deterministic MVP feed showing monitored source items, official updates,
      draft guidance, and trusted news warnings normalized by the web scraping pipeline.
    </p>
  </header>
  <main>
    {"".join(cards)}
  </main>
</body>
</html>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


def generate_web_scraping_outputs(
    source_registry: Path,
    event_seed: Path,
    output_dir: Path,
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)

    sources = load_sources(source_registry)
    static_source = next(
        source for source in sources if source.name == "European Commission AI Office"
    )
    static_items = deduplicate_items(monitor_source_from_html(static_source, STATIC_HTML))
    seed_items = monitored_items_from_event_seed(event_seed, sources)
    events = [event.to_dashboard_dict() for event in group_items_into_events(seed_items)]

    source_snapshot_file = output_dir / "source_registry_snapshot.json"
    scraped_items_file = output_dir / "scraped_monitored_items.json"
    seed_items_file = output_dir / "seed_monitored_items.json"
    events_file = output_dir / "regulatory_events.json"
    article_feed_file = output_dir / "articles_and_news_feed.json"
    article_feed_markdown_file = output_dir / "articles_and_news_feed.md"
    article_feed_html_file = output_dir / "articles_and_news_feed.html"
    summary_file = output_dir / "run_summary.json"
    summary_markdown_file = output_dir / "run_summary.md"
    article_feed = build_article_feed(static_items, events)

    write_json(source_snapshot_file, [asdict(source) for source in sources])
    write_json(scraped_items_file, [asdict(item) for item in static_items])
    write_json(seed_items_file, [asdict(item) for item in seed_items])
    write_json(events_file, events)
    write_json(article_feed_file, article_feed)
    write_article_feed_markdown(article_feed_markdown_file, article_feed)
    write_article_feed_html(article_feed_html_file, article_feed)

    status_counts = Counter(event["event_status"] for event in events)
    priority_counts = Counter(event["overall_priority"] for event in events)
    summary = {
        "output_dir": str(output_dir),
        "source_snapshot": str(source_snapshot_file),
        "scraped_items_file": str(scraped_items_file),
        "seed_items_file": str(seed_items_file),
        "events_file": str(events_file),
        "article_feed_file": str(article_feed_file),
        "article_feed_markdown_file": str(article_feed_markdown_file),
        "article_feed_html_file": str(article_feed_html_file),
        "summary_file": str(summary_file),
        "summary_markdown_file": str(summary_markdown_file),
        "sources_loaded": len(sources),
        "static_scraped_items": len(static_items),
        "seed_monitored_items": len(seed_items),
        "regulatory_events": len(events),
        "article_feed_items": len(article_feed),
        "status_counts": dict(sorted(status_counts.items())),
        "priority_counts": dict(sorted(priority_counts.items())),
    }
    write_json(summary_file, summary)
    write_markdown_summary(summary_markdown_file, summary, events)
    return summary
